# Generated by Django 5.1 on 2024-09-13 09:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RunsRecord',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('uuid', models.TextField()),
                ('runTime', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Run',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('numberOfAgent', models.IntegerField()),
                ('simulationPeriod', models.IntegerField()),
                ('uuid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='src.runsrecord')),
            ],
        ),
    ]
