# Generated by Django 5.1 on 2024-10-05 07:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Simulation',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('numberOfAgent', models.IntegerField()),
                ('simulationPeriod', models.IntegerField()),
                ('createDate', models.DateField()),
                ('updateDate', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.IntegerField(primary_key=True, serialize=False)),
                ('username', models.TextField()),
                ('password', models.TextField()),
                ('lastSignedOn', models.DateTimeField()),
                ('createDate', models.DateField()),
            ],
        ),
        migrations.RemoveField(
            model_name='runsrecord',
            name='uuid',
        ),
        migrations.CreateModel(
            name='Modes',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('location', models.TextField()),
                ('createDate', models.DateField()),
                ('updateDate', models.DateField()),
                ('createdBy', models.TextField()),
                ('simulation_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='src.simulation')),
            ],
        ),
        migrations.CreateModel(
            name='Files',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('filename', models.TextField()),
                ('location', models.TextField()),
                ('createDate', models.DateField()),
                ('updateDate', models.DateField()),
                ('simulation_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='src.simulation')),
            ],
        ),
        migrations.AddField(
            model_name='runsrecord',
            name='simulation_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='src.simulation'),
        ),
        migrations.AddField(
            model_name='simulation',
            name='createdBy',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='src.user'),
        ),
        migrations.DeleteModel(
            name='Run',
        ),
    ]
