# Generated by Django 5.1 on 2024-10-10 23:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0002_simulation_user_remove_runsrecord_uuid_modes_files_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Files',
            new_name='File',
        ),
        migrations.RenameModel(
            old_name='Modes',
            new_name='Mode',
        ),
    ]
