# Generated by Django 5.1 on 2024-10-25 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0003_rename_files_file_rename_modes_mode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='simulation',
            name='updateDate',
            field=models.DateField(null=True),
        ),
    ]
