# Generated by Django 5.1 on 2024-11-04 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0004_alter_simulation_updatedate'),
    ]

    operations = [
        migrations.AddField(
            model_name='simulation',
            name='name',
            field=models.TextField(default=''),
        ),
    ]
