# Generated by Django 5.1 on 2024-11-08 04:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0005_simulation_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='simulation',
            name='createdBy',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='file',
            name='simulation_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='src.simulation'),
        ),
        migrations.AlterField(
            model_name='mode',
            name='simulation_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='src.simulation'),
        ),
        migrations.AlterField(
            model_name='runsrecord',
            name='simulation_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='src.simulation'),
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
