# Generated by Django 5.1 on 2025-02-15 04:00

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0006_alter_simulation_createdby_alter_file_simulation_id_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Simulation',
            new_name='SimulationRun',
        ),
        migrations.AddField(
            model_name='mode',
            name='user',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
