# Generated by Django 5.1 on 2025-04-11 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0007_rename_simulation_simulationrun_mode_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mode',
            name='updateDate',
            field=models.DateField(null=True),
        ),
    ]
