# Generated by Django 5.1 on 2025-04-11 01:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0008_alter_mode_updatedate'),
    ]

    operations = [
        migrations.RenameField(
            model_name='file',
            old_name='simulation_id',
            new_name='simulation',
        ),
        migrations.RenameField(
            model_name='mode',
            old_name='simulation_id',
            new_name='simulation',
        ),
        migrations.RenameField(
            model_name='runsrecord',
            old_name='simulation_id',
            new_name='simulation',
        ),
    ]
