# Generated by Django 5.1 on 2025-04-11 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0009_rename_simulation_id_file_simulation_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='updateDate',
            field=models.DateField(null=True),
        ),
    ]
