# Generated by Django 5.2.5 on 2026-01-02 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0010_alter_file_updatedate'),
    ]

    operations = [
        migrations.AddField(
            model_name='runsrecord',
            name='status',
            field=models.TextField(choices=[('CREATED', 'Created'), ('IN_PROGRESS', 'In progress'), ('DONE', 'Done'), ('ERROR', 'Error'), ('UNDERTERMINED', 'Undetermined')], default='UNDERTERMINED'),
        ),
    ]
