# Generated by Django 5.2.5 on 2026-01-16 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0012_runsrecord_createdby'),
    ]

    operations = [
        migrations.AlterField(
            model_name='runsrecord',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
